<?php

namespace Symbio\OrangeGate\TranslationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageCatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageCatalogueRepository extends EntityRepository
{
}
