<?php

namespace Symbio\OrangeGate\TranslationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageTranslationRepository extends EntityRepository
{
	/**
     * Return all translations for specified token
     * @param type $token
     * @param type $domain
     */
    public function getTranslations($language, $catalogue = "messages"){
        $query = $this->getEntityManager()->createQuery("SELECT t FROM SymbioOrangeGateTranslationBundle:LanguageTranslation t LEFT JOIN t.languageToken tt LEFT JOIN tt.catalogue c  WHERE t.language = :language AND c.name = :catalogue");
        $query->setParameter("language", $language);
        $query->setParameter("catalogue", $catalogue);

        return $query->getResult();
    }
}
